import React, { Component } from "react";

const MyContext = React.createContext();

export default class MyProvider extends Component {
 constructor(props) {
     super(props)
 
     this.state = {
        flip: this.flip,
        trends: [
          { key: 0, label: "trends", url: "" },
          //everything will be pushed, thus the "trend" obj will be the only permanent item of the arr
          //PUPPETS WILL LOAD DATA TO THE DATAbase
          {
            url: "https://www.aljazeera.com/ajimpact/",
            key: `${Math.random()}`,
            label: "Pitch Black Afro",
          },
          {
            url: "https://www.aljazeera.com/ajimpact/",
            key: `${Math.random()}`,
            label: "Taxi Strike",
          },
          {
            url: "https://www.aljazeera.com/ajimpact/",
            key: `${Math.random()}`,
            label: "Twitter",
          },
          {
            url: "https://www.aljazeera.com/ajimpact/",
            key: `${Math.random()}`,
            label: "Zara",
          },
          {
            url: "https://www.aljazeera.com/ajimpact/",
            key: `${Math.random()}`,
            label: "Soccer",
          },
          {
            url: "https://www.aljazeera.com/ajimpact/",
            key: `${Math.random()}`,
            label: "Jazz Fest",
          },
          {
            url: "https://www.aljazeera.com/ajimpact/",
            key: `${Math.random()}`,
            label: "BLM",
          },
          {
            url: "https://www.aljazeera.com/ajimpact/",
            key: `${Math.random()}`,
            label: "Hauwei",
          },
          {
            url: "https://www.aljazeera.com/ajimpact/",
            key: `${Math.random()}`,
            label: "Covid-19",
          },
          {
            url: "https://www.aljazeera.com/ajimpact/",
            key: `${Math.random()}`,
            label: "Trump",
          }
        ],
        arr: [
       
          [
            {
              "id": "50s8n9tpafs5tnl1hs2lap1vqtri1kw6",
              "url": "https://citizen.co.za/news/south-africa/local-news/2421175/r12m-bronkhorstspruit-hospital-upgrade-makes-no-sense/",
              "headline": "R12m Bronkhorstspruit hospital upgrade ‘makes no sense’",
              "lede": "Last June, BMW Germany announced the company would partner with the government to upgrade…",
              "thumbnail": "https://citizen.co.za/wp-content/uploads/2018/02/bronks-389x259.jpg?x79228",
              "category": "sport",
              "catLink": "local news",
              "images": null,
              "key": null,
              "label": null,
              "subject": null,
              "format": null,
              "about": null,
              "src_name": "Citizen",
              "src_url": "https://citizen.co.za",
              "src_logo": "https://citizen.co.za/wp-content/themes/citizen-v5-2/images/citizen_logo_footer_v2.png",
              "isVid": false,
              "vidLen": null,
              "type": "strip",
              "tag": "local news",
              "tags": null,
              "author": null,
              "authors": null,
              "date": null,
              "created_at": "2021-01-18T04:36:55.000000Z",
              "updated_at": "2021-01-18T04:36:55.000000Z"
          },
          {
              "id": "hkzdcrod52f0kuw7hqqgwwv5yflx60u7",
              "url": "https://www.bbc.com/news/business-55669168",
              "headline": "Scottish fishermen 'landing fish in Denmark'",
              "lede": null,
              "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/73AE/production/_116541692_scottishfishermen.jpg",
              "category": "Business",
              "catLink": null,
              "images": null,
              "key": null,
              "label": null,
              "subject": null,
              "format": null,
              "about": null,
              "src_name": "BBC",
              "src_url": "https://www.bbc.com",
              "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
              "isVid": false,
              "vidLen": null,
              "type": "card",
              "tag": "Business",
              "tags": null,
              "author": null,
              "authors": null,
              "date": "2 days ago",
              "created_at": "2021-01-18T10:08:45.000000Z",
              "updated_at": "2021-01-18T10:08:45.000000Z"
          },
          {
              "id": "hf0yuveunh48xpdrfn3g6rorlibynpbo",
              "url": "https://www.bbc.com/news/business-55158959",
              "headline": "Smart locks: Convenience comes with security doubts",
              "lede": null,
              "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/175F0/production/_115982759_phone.lock.gettyimages-922685814.jpg",
              "category": null,
              "catLink": null,
              "images": null,
              "key": null,
              "label": null,
              "subject": null,
              "format": null,
              "about": null,
              "src_name": "BBC",
              "src_url": "https://www.bbc.com",
              "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
              "isVid": false,
              "vidLen": null,
              "type": "card",
              "tag": "tech",
              "tags": null,
              "author": null,
              "authors": null,
              "date": null,
              "created_at": "2021-01-18T10:09:18.000000Z",
              "updated_at": "2021-01-18T10:09:18.000000Z"
          },
          ],
          {
            "id": "1s2aqfzd388g0rd91q6joujqdvvujaas",
            "url": "https://news.cgtn.com/news/2021-01-18/-Days-and-Nights-in-Wuhan-documents-ordinary-people-s-COVID-19-battle-X94xngLN9C/index.html",
            "headline": "'Days and Nights in Wuhan' documents ordinary people's COVID-19 battle",
            "lede": null,
            "thumbnail": null,
            "category": "Movie/TV",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "CGTN",
            "src_url": "https://www.cgtn.com",
            "src_logo": "https://ui.cgtn.com/static/ng/resource/images/icon/logo@3x.png",
            "isVid": true,
            "vidLen": "6:29",
            "type": "title-only",
            "tag": "Movie/TV",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "12:15, 18-Jan-2021",
            "created_at": "2021-01-18T09:21:40.000000Z",
            "updated_at": "2021-01-18T09:21:40.000000Z"
        },
        {
            "id": "rnf2jfxt5eoftxjvx922fsvv4cvgr9i5",
            "url": "https://news.cgtn.com/news/2021-01-18/-Elves-of-the-Yangtze-River-show-up-in-central-China-X96xcACSLS/index.html",
            "headline": "'Elves of the Yangtze River' show up in central China",
            "lede": null,
            "thumbnail": "https://ui.cgtn.com/static/ng/resource/images/icon/zwt-bg.png",
            "category": "Animal",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "CGTN",
            "src_url": "https://www.cgtn.com",
            "src_logo": "https://ui.cgtn.com/static/ng/resource/images/icon/logo@3x.png",
            "isVid": true,
            "vidLen": "6:29",
            "type": "title-only",
            "tag": "Animal",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "13:11, 18-Jan-2021",
            "created_at": "2021-01-18T09:22:01.000000Z",
            "updated_at": "2021-01-18T09:22:01.000000Z"
        },
        {
            "id": "p3lcleiza9kk3vemmhokeou8l9xh1fq4",
            "url": "https://www.bbc.com/news/business-55636774",
            "headline": "'I couldn't build a company on my own'",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/53D2/production/_116485412_p093sm9b.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": true,
            "vidLen": "1:19",
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:09:30.000000Z",
            "updated_at": "2021-01-18T10:09:30.000000Z"
        },
        {
            "id": "l8xndmg9nbiqyaunzeue5zu0t5p4g5mr",
            "url": "https://www.bbc.com/news/business-55638969",
            "headline": "'Putting UK, not GB, delayed my fish for 24 hours'",
            "lede": "New trading rules are causing problems for some firms, creating backlogs and uncertainty.",
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/0DDF/production/_116515530_2972d877-3cb0-428a-be41-53425c776870.jpg",
            "category": "Business",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": "6:29",
            "type": "card",
            "tag": "Business",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "9 hours ago",
            "created_at": "2021-01-18T10:06:23.000000Z",
            "updated_at": "2021-01-18T10:06:23.000000Z"
        },
        {
            "id": "1iblzqhoyemmgenk5n12n6gvrif2ofnk",
            "url": "https://www.bbc.com/news/uk-england-derbyshire-55663976",
            "headline": "'This heart gave me another chance at life'",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/14FD3/production/_116517958_p09408fh.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": true,
            "vidLen": "2:45",
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:12:12.000000Z",
            "updated_at": "2021-01-18T10:12:12.000000Z"
        },
        {
            "id": "l5u6z4eeswu25atm8paiheh8f3patr39",
            "url": "https://newseu.cgtn.com/news/2021-01-18/-Vaccine-passports-how-do-they-work-and-what-are-the-dangers--X8cZWsj1JK/index.html",
            "headline": "'Vaccine passports': how do they work and what are the dangers?",
            "lede": null,
            "thumbnail": null,
            "category": "Europe",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "CGTN",
            "src_url": "https://www.cgtn.com",
            "src_logo": "https://ui.cgtn.com/static/ng/resource/images/icon/logo@3x.png",
            "isVid": true,
            "vidLen": "6:29",
            "type": "title-only",
            "tag": "Europe",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "02:12, 18-Jan-2021",
            "created_at": "2021-01-18T09:21:18.000000Z",
            "updated_at": "2021-01-18T09:21:18.000000Z"
        },
        {
            "id": "qd01l6s03uhtyfdbg485401fy3kqi48h",
            "url": "https://www.bbc.com/news/business-55411719",
            "headline": "'We work day in, day out but don't get respect'",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/7C2E/production/_116209713_p0925n1k.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": true,
            "vidLen": "2:59",
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:10:02.000000Z",
            "updated_at": "2021-01-18T10:10:02.000000Z"
        },
        {
            "id": "5101vnhhq9ti5btp7pp1krw5btl58o83",
            "url": "https://www.bbc.com/news/uk-55548820",
            "headline": "A ride that 'just feels safer'",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/59FD/production/_116373032_p093887l.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": true,
            "vidLen": "1:42",
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:09:51.000000Z",
            "updated_at": "2021-01-18T10:09:51.000000Z"
        },
        {
            "id": "k71s2155bcuvr25niqdjclq0l709f5bz",
            "url": "https://www.bbc.co.uk/news/business-55637328",
            "headline": "A wristband that tells your boss if you are unhappy",
            "lede": null,
            "thumbnail": null,
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:06:40.000000Z",
            "updated_at": "2021-01-18T10:06:40.000000Z"
        },
        {
            "id": "28ackjmj832hddi5gc6umojqw38cw0to",
            "url": "http://news.bbc.co.uk/1/hi/in_depth/business/aerospace/",
            "headline": "Aerospace",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/11E64/production/_102561337_1gettyimages-1000179032.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:10:56.000000Z",
            "updated_at": "2021-01-18T10:10:56.000000Z"
        },
        {
            "id": "ttmnrkc7k3333iobq4fqzms4za3wop2k",
            "url": "www.website.com/new-page",
            "headline": "African airlines survive covid-19 [Business Africa]",
            "lede": null,
            "thumbnail": "https://static.euronews.com/articles/stories/05/25/40/44/444x249_cmsv2_801f67aa-e618-57e6-a9e1-5dd141b5edf1-5254044.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "Africanews",
            "src_url": "https://www.africanews.com",
            "src_logo": "https://www.screenafrica.com/wp-content/uploads/2018/04/Africanews-logo.png",
            "isVid": true,
            "vidLen": "11:16",
            "type": "strip",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T04:23:08.000000Z",
            "updated_at": "2021-01-18T04:23:08.000000Z"
        },
        {
            "id": "t7a5v4l5uv9wud605ps1nws9wf7dz4a8",
            "url": "https://newsaf.cgtn.com/news/2021-01-17/Air-travel-down-60-percent-as-airline-industry-losses-top-370-bln-X6QC5lgt7G/index.html",
            "headline": "Air travel down 60 percent as airline industry losses top $370 bln",
            "lede": null,
            "thumbnail": null,
            "category": "World",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "CGTN",
            "src_url": "https://www.cgtn.com",
            "src_logo": "https://ui.cgtn.com/static/ng/resource/images/icon/logo@3x.png",
            "isVid": true,
            "vidLen": null,
            "type": "title-only",
            "tag": "World",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "02:07, 17-Jan-2021",
            "created_at": "2021-01-18T09:22:23.000000Z",
            "updated_at": "2021-01-18T09:22:23.000000Z"
        },
        {
            "id": "47n5mnxa5qvt0r8w4w0hswlflivn6wti",
            "url": "https://www.bbc.com/news/business-11876811",
            "headline": "BBC World News business headlines",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/mcs/media/images/66951000/jpg/_66951438_biz_heads_640x360_with_logo.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:09:35.000000Z",
            "updated_at": "2021-01-18T10:09:35.000000Z"
        },
        {
            "id": "oi8y224jr30gd87ujnmift2qj3gu0b4i",
            "url": "https://www.bbc.com/news/health-55681051",
            "headline": "Blood plasma treatment 'does not cut Covid deaths'",
            "lede": "Donations of plasma from people who have recovered from the virus have been suspended.",
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/1329/production/_114250940_tv063164154.jpg",
            "category": "Health",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": "Health",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "2 days ago",
            "created_at": "2021-01-18T10:09:24.000000Z",
            "updated_at": "2021-01-18T10:09:24.000000Z"
        },
        {
            "id": "6wqyeyqm1qsxribzztdfo78h54es62i1",
            "url": "https://news.cgtn.com/news/2021-01-18/Brady-Bucs-end-playoffs-for-Saints-Brees-30-20-X9s0LYvgl2/index.html",
            "headline": "Brady, Bucs, end playoffs for Saints, Brees, 30-20",
            "lede": null,
            "thumbnail": "https://ui.cgtn.com/static/ng/resource/images/icon/zwt-bg.png",
            "category": "NFL",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "CGTN",
            "src_url": "https://www.cgtn.com",
            "src_logo": "https://ui.cgtn.com/static/ng/resource/images/icon/logo@3x.png",
            "isVid": true,
            "vidLen": null,
            "type": "title-only",
            "tag": "NFL",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "16:33, 18-Jan-2021",
            "created_at": "2021-01-18T09:21:45.000000Z",
            "updated_at": "2021-01-18T09:21:45.000000Z"
        },
        {
            "id": "ed192ppamnve1f8bjc2ct1jun2y1pdn4",
            "url": "https://news.cgtn.com/news/2021-01-18/Branson-s-Virgin-Orbit-reaches-space-for-first-time-X8WS3TcMcE/index.html",
            "headline": "Branson's Virgin Orbit reaches space for first time",
            "lede": null,
            "thumbnail": null,
            "category": "Technology",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "CGTN",
            "src_url": "https://www.cgtn.com",
            "src_logo": "https://ui.cgtn.com/static/ng/resource/images/icon/logo@3x.png",
            "isVid": true,
            "vidLen": null,
            "type": "title-only",
            "tag": "Technology",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "10:04, 18-Jan-2021",
            "created_at": "2021-01-18T09:21:23.000000Z",
            "updated_at": "2021-01-18T09:21:23.000000Z"
        },
        {
            "id": "hj7z4td43d5ojh8f70nkph8y5aqrxyba",
            "url": "https://news.cgtn.com/news/2021-01-18/Brazil-approves-emergency-use-of-Sinovac-AstraZeneca-vaccines-X8UehCbu0w/index.html",
            "headline": "Brazil approves emergency use of Sinovac, AstraZeneca vaccines",
            "lede": null,
            "thumbnail": null,
            "category": "Health",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "CGTN",
            "src_url": "https://www.cgtn.com",
            "src_logo": "https://ui.cgtn.com/static/ng/resource/images/icon/logo@3x.png",
            "isVid": true,
            "vidLen": null,
            "type": "title-only",
            "tag": "Health",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "11:31, 18-Jan-2021",
            "created_at": "2021-01-18T09:21:12.000000Z",
            "updated_at": "2021-01-18T09:21:12.000000Z"
        },
        {
            "id": "d3jwxuo34xumw55jmi3kaucozlh5ksip",
            "url": "https://www.bbc.com/news/world-latin-america-55670318",
            "headline": "Brazil hospitals 'lack oxygen' for virus patients",
            "lede": "Reports from Manaus say medical staff are begging for help in a critical situation due to Covid-19.",
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/BF7E/production/_116522094_ffb074cb-b4ac-4c03-99ff-28e41ff913f9.jpg",
            "category": "Latin America & Caribbean",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": "Latin America & Caribbean",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "2 days ago",
            "created_at": "2021-01-18T10:09:40.000000Z",
            "updated_at": "2021-01-18T10:09:40.000000Z"
        },
        {
            "id": "dct6n54fub1hsluf8de43tglchod0fph",
            "url": "https://www.bbc.com/news/business-55699033",
            "headline": "BT faces lawsuit over landline 'overcharging'",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/4A8D/production/_116558091_elderly-man-phone.jpg",
            "category": "Business",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": "Business",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "9 hours ago",
            "created_at": "2021-01-18T10:08:12.000000Z",
            "updated_at": "2021-01-18T10:08:12.000000Z"
        },
        {
            "id": "r2zjt3uagxhfuorciq85ogn2ytfjuuza",
            "url": "https://www.bbc.com/news/business-55666973",
            "headline": "Can supermarket security guards help with mask rules?",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/807B/production/_116519823_p0940bh3.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": true,
            "vidLen": "1:45",
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:09:02.000000Z",
            "updated_at": "2021-01-18T10:09:02.000000Z"
        },
        {
            "id": "9ep3rgja9ol2vfqon3g5f0v93c1366qi",
            "url": "https://www.bbc.com/news/explainers-55680305",
            "headline": "Can you catch coronavirus outside?",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/183DD/production/_116539299_city.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:12:01.000000Z",
            "updated_at": "2021-01-18T10:12:01.000000Z"
        },
        {
            "id": "34h8mwtngyb7ngplbcvq6aknyqp9vytt",
            "url": "https://www.bbc.com/news/business-55699971",
            "headline": "China's growth accelerates, bucking global trend",
            "lede": "Annual growth of 2.3% puts China on course to be the only major economy to have expanded in 2020.",
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/DCA5/production/_116558465_gettyimages-1295054489.jpg",
            "category": "Business",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": "Business",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "6 hours ago",
            "created_at": "2021-01-18T10:06:17.000000Z",
            "updated_at": "2021-01-18T10:06:17.000000Z"
        },
        {
            "id": "9c2rdy6xysbvy0of12yvyr6jlmbloi7h",
            "url": "https://news.cgtn.com/news/2021-01-18/China-s-shipbuilding-industry-keeps-world-leading-role-in-2020-X94VgCaRtm/index.html",
            "headline": "China's shipbuilding industry keeps world-leading role in 2020",
            "lede": null,
            "thumbnail": null,
            "category": "Economy",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "CGTN",
            "src_url": "https://www.cgtn.com",
            "src_logo": "https://ui.cgtn.com/static/ng/resource/images/icon/logo@3x.png",
            "isVid": true,
            "vidLen": "6:29",
            "type": "title-only",
            "tag": "Economy",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "12:01, 18-Jan-2021",
            "created_at": "2021-01-18T09:21:07.000000Z",
            "updated_at": "2021-01-18T09:21:07.000000Z"
        },
        {
            "id": "k8dvffgsgjb38a1p4jyrpnqvg4cikt7q",
            "url": "https://www.bbc.com/news/world-europe-55592161",
            "headline": "Chocolates and beer: Buying from Belgium after Brexit",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/114A4/production/_116402807_p093hyjk.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": true,
            "vidLen": "2:18",
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:09:45.000000Z",
            "updated_at": "2021-01-18T10:09:45.000000Z"
        },
        {
            "id": "5jovny1gt0w3m4y9d0mbdyfezenp04ea",
            "url": "https://www.bbc.com/news/uk-55696244",
            "headline": "Covid-19 jabs done 'four times' faster than new cases",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/9371/production/_116554773_p0948lns.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": true,
            "vidLen": "1:25",
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:12:18.000000Z",
            "updated_at": "2021-01-18T10:12:18.000000Z"
        },
        {
            "id": "bl7rp4vxu8gyru1fk0s97x1p0p0d2zwc",
            "url": "https://news.cgtn.com/news/2021-01-18/Dubai-unveils-key-pavilion-for-Expo-2020-highlighting-sustainability-X9osY7xGCY/index.html",
            "headline": "Dubai unveils key pavilion for Expo 2020 highlighting sustainability",
            "lede": null,
            "thumbnail": null,
            "category": "Culture",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "CGTN",
            "src_url": "https://www.cgtn.com",
            "src_logo": "https://ui.cgtn.com/static/ng/resource/images/icon/logo@3x.png",
            "isVid": true,
            "vidLen": "6:29",
            "type": "title-only",
            "tag": "Culture",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "15:55, 18-Jan-2021",
            "created_at": "2021-01-18T09:21:34.000000Z",
            "updated_at": "2021-01-18T09:21:34.000000Z"
        },
        {
            "id": "ssx5jycmlra7h4dzag0of4yvnyv7dzzj",
            "url": "https://www.bbc.com/news/world-europe-55666399",
            "headline": "EU nations hit by delayed Pfizer vaccine deliveries",
            "lede": "Many EU countries are receiving significantly fewer doses due to a change in manufacturing processes.",
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/57FA/production/_116522522_pfizer.jpg",
            "category": "Europe",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": "Europe",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "2 days ago",
            "created_at": "2021-01-18T10:08:57.000000Z",
            "updated_at": "2021-01-18T10:08:57.000000Z"
        },
        {
            "id": "w48x2hjnig7soqgpa0jswpsrxwwbac6x",
            "url": "https://news.cgtn.com/news/2021-01-18/Fiat-Chrysler-and-PSA-seal-merger-to-become-Stellantis-X8VWunpJ2E/index.html",
            "headline": "Fiat Chrysler and PSA seal merger to become Stellantis",
            "lede": null,
            "thumbnail": "https://ui.cgtn.com/static/ng/resource/images/icon/zwt-bg.png",
            "category": "Company",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "CGTN",
            "src_url": "https://www.cgtn.com",
            "src_logo": "https://ui.cgtn.com/static/ng/resource/images/icon/logo@3x.png",
            "isVid": true,
            "vidLen": "6:29",
            "type": "title-only",
            "tag": "Company",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "12:02, 18-Jan-2021",
            "created_at": "2021-01-18T09:20:56.000000Z",
            "updated_at": "2021-01-18T09:20:56.000000Z"
        },
        {
            "id": "p059rycq3njusxlb0vffw676cxzs6pc3",
            "url": "https://www.bbc.com/news/world-53311792",
            "headline": "Five things you should know about Jeff Bezos",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/CD38/production/_113263525_p08k1hxy.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": true,
            "vidLen": "6:29",
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:10:13.000000Z",
            "updated_at": "2021-01-18T10:10:13.000000Z"
        },
        {
            "id": "n95mxukkg9jqi7fnt71s7jq6sganach5",
            "url": "https://news.cgtn.com/news/2021-01-18/Food-to-eat-in-China-when-it-s-freezing-outside-X9alLfdlNC/index.html",
            "headline": "Food to eat in China when it's freezing outside",
            "lede": null,
            "thumbnail": "https://ui.cgtn.com/static/ng/resource/images/icon/zwt-bg.png",
            "category": "Culture",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "CGTN",
            "src_url": "https://www.cgtn.com",
            "src_logo": "https://ui.cgtn.com/static/ng/resource/images/icon/logo@3x.png",
            "isVid": true,
            "vidLen": null,
            "type": "title-only",
            "tag": "Culture",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "16:58, 18-Jan-2021",
            "created_at": "2021-01-18T09:21:29.000000Z",
            "updated_at": "2021-01-18T09:21:29.000000Z"
        },
        {
            "id": "6f0blz2r7s7wabs1faew6fgmywx9p3xu",
            "url": "https://news.cgtn.com/news/2021-01-18/France-suggests-pause-on-U-S-EU-trade-standoff-X8ViXKp2tW/index.html",
            "headline": "France suggests pause on U.S.-EU trade standoff",
            "lede": null,
            "thumbnail": null,
            "category": "Economy",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "CGTN",
            "src_url": "https://www.cgtn.com",
            "src_logo": "https://ui.cgtn.com/static/ng/resource/images/icon/logo@3x.png",
            "isVid": true,
            "vidLen": null,
            "type": "title-only",
            "tag": "Economy",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "12:01, 18-Jan-2021",
            "created_at": "2021-01-18T09:21:01.000000Z",
            "updated_at": "2021-01-18T09:21:01.000000Z"
        },
        {
            "id": "l4sz2gi9xhaglcgl2ii32308ao9dfbxq",
            "url": "http://news.bbc.co.uk/1/hi/in_depth/business/2009/carmakers/default.stm",
            "headline": "Global Car Industry",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/mcs/media/images/77958000/jpg/_77958343_77958342.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:10:40.000000Z",
            "updated_at": "2021-01-18T10:10:40.000000Z"
        },
        {
            "id": "iv2vle2rxue63z5wlwwmuep7dykjjvnj",
            "url": "https://www.bbc.com/news/business-55696664",
            "headline": "Government urged to 'safeguard' Eurostar's future",
            "lede": "A group of London firms has written to ministers calling for financial support for the rail firm.",
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/EC8B/production/_116555506_gettyimages-1230380632.jpg",
            "category": "Business",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": "Business",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "16 hours ago",
            "created_at": "2021-01-18T10:06:34.000000Z",
            "updated_at": "2021-01-18T10:06:34.000000Z"
        },
        {
            "id": "llxzlfcfvjg5xr7rxy3yyxfiv27yc7kp",
            "url": "https://www.bbc.com/news/business-55630144",
            "headline": "Has coronavirus made us more ethical consumers?",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/15B9F/production/_116419988_img_7483.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:09:13.000000Z",
            "updated_at": "2021-01-18T10:09:13.000000Z"
        },
        {
            "id": "ff02rywre751p621r0lzfvw9u64e5b0e",
            "url": "https://www.bbc.com/news/world-asia-india-55467980",
            "headline": "How India is readying for its massive vaccine drive",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/4E02/production/_116407991_mediaitem116407990.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:12:07.000000Z",
            "updated_at": "2021-01-18T10:12:07.000000Z"
        },
        {
            "id": "2mof1y36mfirwjybkpdg5lii2072nu27",
            "url": "https://www.bbc.com/news/health-55659820",
            "headline": "How worrying are the new coronavirus variants?",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/5DAD/production/_116518932_index_covid_variants_976.png",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:11:51.000000Z",
            "updated_at": "2021-01-18T10:11:51.000000Z"
        },
        {
            "id": "qsjysti2mq7fusv9xr6b3w0899v1a7aa",
            "url": "https://www.bbc.com/news/uk-politics-55696243",
            "headline": "Increased UK border checks for Covid infections - Raab",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/1E41/production/_116554770_p0948kcy.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": true,
            "vidLen": "1:19",
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:12:23.000000Z",
            "updated_at": "2021-01-18T10:12:23.000000Z"
        },
        {
            "id": "30mqykrtpg4ufgj9mzio6xnbtactf5ry",
            "url": "https://www.bbc.com/news/world-asia-india-55632782",
            "headline": "India begins world's biggest Covid vaccine drive",
            "lede": "Health and frontline workers are first in line for jabs at vaccination centres across the country.",
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/0C52/production/_116545130_gettyimages-1230608596.jpg",
            "category": "India",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": true,
            "vidLen": "2:10",
            "type": "card",
            "tag": "India",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "2 days ago",
            "created_at": "2021-01-18T10:09:08.000000Z",
            "updated_at": "2021-01-18T10:09:08.000000Z"
        },
        {
            "id": "22zjhkvg2cj0m80x3eyhbl5gfojgqdsl",
            "url": "https://news.cgtn.com/news/2021-01-18/Liverpool-held-to-goalless-draw-by-Man-United-X92FdBvVh6/index.html",
            "headline": "Liverpool held to goalless draw by Man United",
            "lede": null,
            "thumbnail": null,
            "category": "Football",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "CGTN",
            "src_url": "https://www.cgtn.com",
            "src_logo": "https://ui.cgtn.com/static/ng/resource/images/icon/logo@3x.png",
            "isVid": true,
            "vidLen": null,
            "type": "title-only",
            "tag": "Football",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "11:13, 18-Jan-2021",
            "created_at": "2021-01-18T09:21:56.000000Z",
            "updated_at": "2021-01-18T09:21:56.000000Z"
        },
        {
            "id": "lw1hwrne9v672ohlngke4506jho3jtxo",
            "url": "https://www.bbc.com/news/business-55664266",
            "headline": "Lumley 'shocked' at claims disabled workers unpaid",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/B5FF/production/_116519564_joannalumley.jpg",
            "category": "Business",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": "Business",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "2 days ago",
            "created_at": "2021-01-18T10:08:34.000000Z",
            "updated_at": "2021-01-18T10:08:34.000000Z"
        },
        {
            "id": "iedmlz3bj7c2xgyzo94myxnurot2vdw3",
            "url": "https://www.bbc.co.uk/news/business-45489065",
            "headline": "New Economy",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/6F41/production/_112718482_nicole4.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:10:29.000000Z",
            "updated_at": "2021-01-18T10:10:29.000000Z"
        },
        {
            "id": "3u0suqio78zez026ywdm1ywqgyhbsx5l",
            "url": "https://news.cgtn.com/news/2021-01-17/On-the-road-alone-An-unhappy-housewife-s-escape-X1ln68ngXK/index.html",
            "headline": "On the road alone: An unhappy housewife's escape",
            "lede": null,
            "thumbnail": null,
            "category": "Feature",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "CGTN",
            "src_url": "https://www.cgtn.com",
            "src_logo": "https://ui.cgtn.com/static/ng/resource/images/icon/logo@3x.png",
            "isVid": true,
            "vidLen": null,
            "type": "title-only",
            "tag": "Feature",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "14:56, 17-Jan-2021",
            "created_at": "2021-01-18T09:20:50.000000Z",
            "updated_at": "2021-01-18T09:20:50.000000Z"
        },
        {
            "id": "k6uvsgvusqo7iek64ir5h6t4uu0v7zt0",
            "url": "https://www.bbc.com/news/business-55680315",
            "headline": "Post-Brexit customs systems ‘not fit for purpose’",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/2317/production/_116538980_meat_pa.jpg",
            "category": "Business",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": "Business",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "2 days ago",
            "created_at": "2021-01-18T10:08:01.000000Z",
            "updated_at": "2021-01-18T10:08:01.000000Z"
        },
        {
            "id": "rksuednp96jx8le1ehnq8lwttx85ebt9",
            "url": "https://www.bbc.com/news/business-54900418",
            "headline": "Protecting fragile ecosystems from lithium mining",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/14626/production/_115749438_gettyimages-1277745973.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:08:50.000000Z",
            "updated_at": "2021-01-18T10:08:50.000000Z"
        },
        {
            "id": "50s8n9tpafs5tnl1hs2lap1vqtri1kw36",
            "url": "https://citizen.co.za/news/south-africa/local-news/2421175/r12m-bronkhorstspruit-hospital-upgrade-makes-no-sense/",
            "headline": "R12m Bronkhorstspruit hospital upgrade ‘makes no sense’",
            "lede": "Last June, BMW Germany announced the company would partner with the government to upgrade…",
            "thumbnail": "https://citizen.co.za/wp-content/uploads/2018/02/bronks-389x259.jpg?x79228",
            "category": "sport",
            "catLink": "local news",
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "Citizen",
            "src_url": "https://citizen.co.za",
            "src_logo": "https://citizen.co.za/wp-content/themes/citizen-v5-2/images/citizen_logo_footer_v2.png",
            "isVid": false,
            "vidLen": null,
            "type": "strip",
            "tag": "local news",
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T04:36:55.000000Z",
            "updated_at": "2021-01-18T04:36:55.000000Z"
        },
        {
            "id": "hkzdcrod52f0kuw7hqqgwwv5yflx60u7",
            "url": "https://www.bbc.com/news/business-55669168",
            "headline": "Scottish fishermen 'landing fish in Denmark'",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/73AE/production/_116541692_scottishfishermen.jpg",
            "category": "Business",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": "Business",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "2 days ago",
            "created_at": "2021-01-18T10:08:45.000000Z",
            "updated_at": "2021-01-18T10:08:45.000000Z"
        },
        {
            "id": "hf0yuveunh48xpdrfn3g6rorlibynpbo",
            "url": "https://www.bbc.com/news/business-55158959",
            "headline": "Smart locks: Convenience comes with security doubts",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/175F0/production/_115982759_phone.lock.gettyimages-922685814.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:09:18.000000Z",
            "updated_at": "2021-01-18T10:09:18.000000Z"
        },
        {
            "id": "gk6547l14icw4n6blemp17gbuffkd7pq",
            "url": "https://news.cgtn.com/news/2021-01-18/Snooker-China-s-Yan-Bingtao-wins-Masters-title-on-debut-X90x4amMeI/index.html",
            "headline": "Snooker: China's Yan Bingtao wins Masters title on debut",
            "lede": null,
            "thumbnail": null,
            "category": "Snooker",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "CGTN",
            "src_url": "https://www.cgtn.com",
            "src_logo": "https://ui.cgtn.com/static/ng/resource/images/icon/logo@3x.png",
            "isVid": true,
            "vidLen": "02:45",
            "type": "title-only",
            "tag": "Snooker",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "12:13, 18-Jan-2021",
            "created_at": "2021-01-18T09:21:51.000000Z",
            "updated_at": "2021-01-18T09:21:51.000000Z"
        },
        {
            "id": "ejeavmcjr9smcnj7wg6y4nswes5i4seg",
            "url": "https://news.cgtn.com/news/2021-01-18/Special-cherry-blossoms-dye-a-valley-pink-in-SW-China-X9oW0Ck8k8/index.html",
            "headline": "Special cherry blossoms dye a valley pink in SW China",
            "lede": null,
            "thumbnail": null,
            "category": "Plant",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "CGTN",
            "src_url": "https://www.cgtn.com",
            "src_logo": "https://ui.cgtn.com/static/ng/resource/images/icon/logo@3x.png",
            "isVid": true,
            "vidLen": null,
            "type": "title-only",
            "tag": "Plant",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "15:27, 18-Jan-2021",
            "created_at": "2021-01-18T09:22:07.000000Z",
            "updated_at": "2021-01-18T09:22:07.000000Z"
        },
        {
            "id": "qurg817k2f7kvvfofeqa2o1unfaxteae",
            "url": "http://www.bbc.co.uk/news/business-11428889",
            "headline": "Technology of Business",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/10F23/production/_92611496_thinkstockphotos-517406978.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:10:24.000000Z",
            "updated_at": "2021-01-18T10:10:24.000000Z"
        },
        {
            "id": "kxuf0chz64u93lp7zga172yw9wz0u1t7",
            "url": "https://www.bbc.com/news/world-middle-east-55563798",
            "headline": "The doctor alone in a Covid-ravaged hospital",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/17887/production/_116519369_zoha_tall.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:11:45.000000Z",
            "updated_at": "2021-01-18T10:11:45.000000Z"
        },
        {
            "id": "729ipy6n6uswb59nqx1084e7bicnyqd7",
            "url": "https://news.cgtn.com/news/2021-01-18/The-magic-mushroom-hidden-in-Hainan-s-tropical-rainforest-X99zsXOZyM/index.html",
            "headline": "The magic mushroom hidden in Hainan's tropical rainforest",
            "lede": null,
            "thumbnail": null,
            "category": "Plant",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "CGTN",
            "src_url": "https://www.cgtn.com",
            "src_logo": "https://ui.cgtn.com/static/ng/resource/images/icon/logo@3x.png",
            "isVid": true,
            "vidLen": null,
            "type": "title-only",
            "tag": "Plant",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "12:30, 18-Jan-2021",
            "created_at": "2021-01-18T09:22:12.000000Z",
            "updated_at": "2021-01-18T09:22:12.000000Z"
        },
        {
            "id": "3e7qsa3ahk5tp7byv3fx1jx2xu2lcbjt",
            "url": "https://www.bbc.co.uk/news/business-46985442",
            "headline": "The Rivals",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/3A67/production/_113615941_gettyimages-1212971297.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:10:45.000000Z",
            "updated_at": "2021-01-18T10:10:45.000000Z"
        },
        {
            "id": "2iysatjvsa27i85mp7twpnhz1chckg0b",
            "url": "https://www.bbc.com/news/education-55620288",
            "headline": "Tips for helping your child's mental health",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/10ED4/production/_116523396_p0941h31.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": true,
            "vidLen": "2:40",
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:12:28.000000Z",
            "updated_at": "2021-01-18T10:12:28.000000Z"
        },
        {
            "id": "v901i8timgg9vjek1iswiyjc3a5asb93",
            "url": "https://newsaf.cgtn.com/news/2021-01-17/UK-airports-call-for-urgent-govt-support-after-travel-rules-tightened-X6Ll2qVGFi/index.html",
            "headline": "UK airports call for urgent govt support after travel rules tightened",
            "lede": null,
            "thumbnail": null,
            "category": "Europe",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "CGTN",
            "src_url": "https://www.cgtn.com",
            "src_logo": "https://ui.cgtn.com/static/ng/resource/images/icon/logo@3x.png",
            "isVid": true,
            "vidLen": null,
            "type": "title-only",
            "tag": "Europe",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "00:51, 17-Jan-2021",
            "created_at": "2021-01-18T09:22:29.000000Z",
            "updated_at": "2021-01-18T09:22:29.000000Z"
        },
        {
            "id": "ex2vn2eotpp4muo2m1jpw4zmp31rzvhf",
            "url": "https://www.bbc.com/news/uk-55695912",
            "headline": "UK-bound travellers now need negative test for entry",
            "lede": "Passengers must also quarantine for up to 10 days following the closure of all UK travel corridors.",
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/7A99/production/_116558313_mediaitem116558312.jpg",
            "category": "UK",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": "UK",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "6 hours ago",
            "created_at": "2021-01-18T10:06:29.000000Z",
            "updated_at": "2021-01-18T10:06:29.000000Z"
        },
        {
            "id": "rufzd2vveuoc6fge4xkae072aj4b77bp",
            "url": "https://news.cgtn.com/news/2021-01-17/Universal-Studios-Beijing-completes-major-project-X89amNkSE8/index.html",
            "headline": "Universal Studios Beijing completes major project",
            "lede": null,
            "thumbnail": null,
            "category": "Travel",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "CGTN",
            "src_url": "https://www.cgtn.com",
            "src_logo": "https://ui.cgtn.com/static/ng/resource/images/icon/logo@3x.png",
            "isVid": true,
            "vidLen": null,
            "type": "title-only",
            "tag": "Travel",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "21:28, 17-Jan-2021",
            "created_at": "2021-01-18T09:22:18.000000Z",
            "updated_at": "2021-01-18T09:22:18.000000Z"
        },
        {
            "id": "4trksicum0p4pxrm23qep7jwtbbgc2l4",
            "url": "https://www.bbc.com/news/world-us-canada-55684878",
            "headline": "US expects 'rapid growth' of virus variant",
            "lede": "Health officials warn the highly contagious UK Covid variant could become the dominant strain in the US by March.",
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/109D6/production/_116545086_mediaitem116544905.jpg",
            "category": "US & Canada",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": "US & Canada",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "2 days ago",
            "created_at": "2021-01-18T10:08:40.000000Z",
            "updated_at": "2021-01-18T10:08:40.000000Z"
        },
        {
            "id": "6vens1lajc5nawnq0stvq986bpzr1h71",
            "url": "https://www.bbc.com/news/uk-55698132",
            "headline": "Vaccinations to begin for over-70s in England",
            "lede": "Over five million more people will be offered a jab, as 10 new mass vaccination hubs open in England.",
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/AF4B/production/_116557844_hi065198635.jpg",
            "category": "UK",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": "UK",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "7 minutes ago",
            "created_at": "2021-01-18T10:08:29.000000Z",
            "updated_at": "2021-01-18T10:08:29.000000Z"
        },
        {
            "id": "5hjujt9lqxgqeyduf5ytoehgldmafsl8",
            "url": "https://www.bbc.com/news/uk-55692690",
            "headline": "Vaccine patients treated to live organ music",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/14E1F/production/_116553558_p09488r6.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": true,
            "vidLen": "1:03",
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:12:34.000000Z",
            "updated_at": "2021-01-18T10:12:34.000000Z"
        },
        {
            "id": "vk9kteojwso6vdp8adzcndvsf3ocpp3e",
            "url": "https://www.bbc.com/news/technology-55683745",
            "headline": "WhatsApp extends 'confusing' update deadline",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/16264/production/_116542709_gettyimages-1230506428.jpg",
            "category": "Technology",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": "Technology",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "2 days ago",
            "created_at": "2021-01-18T10:08:23.000000Z",
            "updated_at": "2021-01-18T10:08:23.000000Z"
        },
        {
            "id": "5y6p33fjtp3dju3k15nkkzg8lphoc2lw",
            "url": "https://www.bbc.com/news/election-us-2020-55578098",
            "headline": "Why California is struggling to contain Covid",
            "lede": null,
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/13140/production/_116544187_gettyimages-1230050273.jpg",
            "category": null,
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": null,
            "tags": null,
            "author": null,
            "authors": null,
            "date": null,
            "created_at": "2021-01-18T10:11:56.000000Z",
            "updated_at": "2021-01-18T10:11:56.000000Z"
        },
        {
            "id": "4huu2cy15kst0uaevy6huzm9jb1jywg0",
            "url": "https://www.bbc.com/news/business-55652310",
            "headline": "Will the Trump corporate backlash make a difference?",
            "lede": "After the storming of the US Capitol, Donald Trump is facing \"a very different set of calculations\".",
            "thumbnail": "https://ichef.bbci.co.uk/news/490/cpsprodpb/2E9C/production/_116523911_gettyimages-1227768785.jpg",
            "category": "Business",
            "catLink": null,
            "images": null,
            "key": null,
            "label": null,
            "subject": null,
            "format": null,
            "about": null,
            "src_name": "BBC",
            "src_url": "https://www.bbc.com",
            "src_logo": "https://nav.files.bbci.co.uk/orbit/db9d3ece642dbb01f23f791064ec1502/img/blq-orbit-blocks_grey_alpha.png",
            "isVid": false,
            "vidLen": null,
            "type": "card",
            "tag": "Business",
            "tags": null,
            "author": null,
            "authors": null,
            "date": "a day ago",
            "created_at": "2021-01-18T10:06:45.000000Z",
            "updated_at": "2021-01-18T10:06:45.000000Z"
        }
        
        ],
      };

      this.flip = this.flip.bind(this);
 }
 

  flip = (page=1) => {
      this.setState({page})
    console.log(this,{page});
}

  render() {
    return (
      <MyContext.Provider value={this.state}>
        {this.props.children}
      </MyContext.Provider>
    );
  }
}
const MyConsumer = MyContext.Consumer;

export { MyProvider, MyConsumer, MyContext };
